# https://lightning.ai/docs/pytorch/latest/api/lightning.pytorch.callbacks.LearningRateFinder.html

# The LearningRateFinder callback enables auto guess for initial LR value
learning_rate_finder:
  _target_: lightning.pytorch.callbacks.LearningRateFinder
  min_lr: 1e-6
  max_lr: 1e-2
  num_training_steps: 30
  mode: exponential
  early_stop_threshold: null
  update_attr: true
